const DATA_URL='data/nfl_offense_2020_2025.csv';
let allData=[],filtered=[],page=0;const PAGE_SIZE=25;
const $=id=>document.getElementById(id);
const teamNames={ARI:'Arizona',ATL:'Atlanta',BAL:'Baltimore',BUF:'Buffalo',CAR:'Carolina',CHI:'Chicago',CIN:'Cincinnati',CLE:'Cleveland',DAL:'Dallas',DEN:'Denver',DET:'Detroit',GB:'Green Bay',HOU:'Houston',IND:'Indianapolis',JAX:'Jacksonville',KC:'Kansas City',LA:'LA Rams',LAC:'LA Chargers',LV:'Las Vegas',MIA:'Miami',MIN:'Minnesota',NE:'New England',NO:'New Orleans',NYG:'NY Giants',NYJ:'NY Jets',PHI:'Philadelphia',PIT:'Pittsburgh',SEA:'Seattle',SF:'San Francisco',TB:'Tampa Bay',TEN:'Tennessee',WAS:'Washington'};
function parseCSV(text){const lines=text.trim().split(/\r?\n/),h=lines[0].split(',');return lines.slice(1).map(line=>{const v=line.split(','),o={};h.forEach((k,i)=>o[k]=v[i]??'');return normalize(o)})}
function n(v){return v===''?NaN:Number(v)}
function normalize(o){['season','week','qtr','down','ydstogo','yardline_100','yards_gained','pass','rush','first_down','touchdown','turnover','explosive_play','epa','success','score_differential'].forEach(k=>o[k]=n(o[k]));return o}
function initSelect(el,values,allLabel='All'){el.innerHTML=`<option value="">${allLabel}</option>`+values.map(v=>`<option value="${v.value??v}">${v.label??v}</option>`).join('')}
function init(){initSelect($('seasonFilter'),[2020,2021,2022,2023,2024,2025]);initSelect($('teamFilter'),Object.keys(teamNames).sort().map(k=>({value:k,label:`${teamNames[k]} (${k})`})));initSelect($('downFilter'),[1,2,3,4].map(x=>({value:x,label:`${x}${x===1?'st':x===2?'nd':x===3?'rd':'th'}`})));initSelect($('playFilter'),[{value:'Pass',label:'Pass'},{value:'Run',label:'Run'}]);['seasonFilter','teamFilter','downFilter','playFilter','measureSelect','breakdownSelect'].forEach(id=>$(id).addEventListener('change',()=>{page=0;apply()}));$('resetBtn').onclick=()=>{['seasonFilter','teamFilter','downFilter','playFilter'].forEach(id=>$(id).value='');$('measureSelect').value='epa';$('breakdownSelect').value='posteam';page=0;apply()};$('prevPage').onclick=()=>{if(page>0){page--;renderTable()}};$('nextPage').onclick=()=>{if((page+1)*PAGE_SIZE<filtered.length){page++;renderTable()}};window.addEventListener('resize',debounce(renderCharts,120));apply()}
function apply(){const s=$('seasonFilter').value,t=$('teamFilter').value,d=$('downFilter').value,p=$('playFilter').value;filtered=allData.filter(r=>(!s||r.season==s)&&(!t||r.posteam===t)&&(!d||r.down==d)&&(!p||r.play_call===p));renderMetrics();renderCharts();renderTable();const parts=[s&&`Season ${s}`,t&&teamNames[t],d&&`Down ${d}`,p].filter(Boolean);$('filterStatus').textContent=`${filtered.length.toLocaleString()} matching plays${parts.length?' • '+parts.join(' • '):' • All seasons, teams, downs, and play types'}`}
function avg(arr,key){let sum=0,c=0;for(const r of arr){const v=r[key];if(Number.isFinite(v)){sum+=v;c++}}return c?sum/c:NaN}
function renderMetrics(){$('mPlays').textContent=filtered.length.toLocaleString();$('mEPA').textContent=fmt(avg(filtered,'epa'),'epa');$('mSuccess').textContent=fmt(avg(filtered,'success'),'pct');$('mYards').textContent=fmt(avg(filtered,'yards_gained'),'yards')}
const measureLabels={epa:'EPA / Play',success:'Success Rate',yards:'Yards / Play',explosive:'Explosive Play Rate',touchdown:'Touchdown Rate',turnover:'Turnover Rate'};
function metric(rows,m){if(m==='epa')return avg(rows,'epa');if(m==='success')return avg(rows,'success')*100;if(m==='yards')return avg(rows,'yards_gained');if(m==='explosive')return avg(rows,'explosive_play')*100;if(m==='touchdown')return avg(rows,'touchdown')*100;if(m==='turnover')return avg(rows,'turnover')*100;return NaN}
function fmt(v,type){if(!Number.isFinite(v))return '—';if(type==='epa')return v.toFixed(3);if(type==='pct')return (v*100).toFixed(2)+'%';if(type==='yards')return v.toFixed(2);return v.toFixed(2)}
function group(rows,key){const m=new Map();for(const r of rows){let k=r[key];if(!Number.isFinite(k)&&typeof k!=='string')continue;if(k===''||k==null)continue;if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return m}
function labelFor(key,v){if(key==='posteam')return v;if(key==='qtr')return Number(v)>4?'OT':`Q${v}`;if(key==='down')return `Down ${v}`;return String(v)}
function renderCharts(){const measure=$('measureSelect').value,key=$('breakdownSelect').value;const g=group(filtered,key);let items=[...g.entries()].map(([k,rows])=>({label:labelFor(key,k),value:metric(rows,measure),count:rows.length}));if(key==='posteam')items.sort((a,b)=>b.value-a.value);else items.sort((a,b)=>String(a.label).localeCompare(String(b.label),undefined,{numeric:true}));$('mainChartSubtitle').textContent=`${measureLabels[measure]} broken down by ${$('breakdownSelect').selectedOptions[0].text}`;drawBar($('mainChart'),items,measureLabels[measure]);const pg=group(filtered,'play_call');drawBar($('playChart'),['Pass','Run'].map(k=>({label:k,value:metric(pg.get(k)||[],measure),count:(pg.get(k)||[]).length})),measureLabels[measure]);drawScore();drawField(measure)}
function scoreBucket(x){if(x<=-15)return'Behind 15+';if(x<=-8)return'Behind 8-14';if(x<=-1)return'Behind 1-7';if(x===0)return'Tied';if(x<=6)return'Ahead 1-6';if(x<=13)return'Ahead 7-13';return'Ahead 14+'}
function drawScore(){const labels=['Behind 15+','Behind 8-14','Behind 1-7','Tied','Ahead 1-6','Ahead 7-13','Ahead 14+'],map=new Map(labels.map(x=>[x,{Pass:0,Run:0,total:0}]));for(const r of filtered){const b=scoreBucket(r.score_differential),o=map.get(b);o.total++;if(r.play_call==='Pass')o.Pass++;else if(r.play_call==='Run')o.Run++}drawGroupedBar($('scoreChart'),labels.map(l=>({label:l,a:map.get(l).total?map.get(l).Pass/map.get(l).total*100:0,b:map.get(l).total?map.get(l).Run/map.get(l).total*100:0})),'Pass %','Run %')}
function fieldZone(y){if(y<=10)return'Opp 1-10';if(y<=20)return'Opp 11-20';if(y<=50)return'Opp 21-50';if(y<=80)return'Own 21-50';return'Own 1-20'}
function drawField(measure){const order=['Own 1-20','Own 21-50','Opp 21-50','Opp 11-20','Opp 1-10'],m=new Map(order.map(x=>[x,[]]));for(const r of filtered)if(Number.isFinite(r.yardline_100))m.get(fieldZone(r.yardline_100)).push(r);drawBar($('fieldChart'),order.map(k=>({label:k,value:metric(m.get(k),measure),count:m.get(k).length})),measureLabels[measure])}
function setupCanvas(canvas){const rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.max(300,rect.width*dpr);canvas.height=340*dpr;const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);return{c,w:rect.width,h:340}}
function drawBar(canvas,items,yLabel){const {c,w,h}=setupCanvas(canvas);c.clearRect(0,0,w,h);if(!items.length){c.fillText('No data for current filters',20,30);return}const pad={l:55,r:18,t:20,b:70},vals=items.map(x=>x.value).filter(Number.isFinite),min=Math.min(0,...vals),max=Math.max(0,...vals),range=(max-min)||1,plotW=w-pad.l-pad.r,plotH=h-pad.t-pad.b,bw=Math.max(3,plotW/items.length*.68);c.font='12px system-ui';c.fillStyle='#607080';c.strokeStyle='#dce3ea';c.beginPath();c.moveTo(pad.l,pad.t);c.lineTo(pad.l,h-pad.b);c.lineTo(w-pad.r,h-pad.b);c.stroke();const zeroY=pad.t+(max/range)*plotH;c.strokeStyle='#9aa9b7';c.beginPath();c.moveTo(pad.l,zeroY);c.lineTo(w-pad.r,zeroY);c.stroke();items.forEach((it,i)=>{if(!Number.isFinite(it.value))return;const x=pad.l+(i+.5)*plotW/items.length-bw/2,y=pad.t+(max-it.value)/range*plotH,bh=Math.abs(zeroY-y);c.fillStyle='#2463a7';c.fillRect(x,Math.min(y,zeroY),bw,bh);c.save();c.translate(x+bw/2,h-pad.b+8);c.rotate(items.length>10?-Math.PI/3:0);c.textAlign=items.length>10?'right':'center';c.fillStyle='#435466';c.fillText(it.label,0,items.length>10?0:14);c.restore()});c.save();c.translate(14,h/2);c.rotate(-Math.PI/2);c.textAlign='center';c.fillStyle='#607080';c.fillText(yLabel,0,0);c.restore();attachTooltip(canvas,items,pad,plotW,bw,(it)=>`${it.label}: ${formatMeasure(it.value,$('measureSelect').value)} • ${it.count.toLocaleString()} plays`)}
function drawGroupedBar(canvas,items,aLabel,bLabel){const {c,w,h}=setupCanvas(canvas),pad={l:48,r:18,t:28,b:75},plotW=w-pad.l-pad.r,plotH=h-pad.t-pad.b,max=100,groupW=plotW/items.length,bw=groupW*.28;c.clearRect(0,0,w,h);c.strokeStyle='#dce3ea';c.beginPath();c.moveTo(pad.l,pad.t);c.lineTo(pad.l,h-pad.b);c.lineTo(w-pad.r,h-pad.b);c.stroke();items.forEach((it,i)=>{const cx=pad.l+(i+.5)*groupW,ha=it.a/max*plotH,hb=it.b/max*plotH;c.fillStyle='#2463a7';c.fillRect(cx-bw,h-pad.b-ha,bw,ha);c.fillStyle='#e07a2d';c.fillRect(cx,h-pad.b-hb,bw,hb);c.save();c.translate(cx,h-pad.b+12);c.rotate(-Math.PI/5);c.textAlign='right';c.fillStyle='#435466';c.font='11px system-ui';c.fillText(it.label,0,0);c.restore()});c.fillStyle='#2463a7';c.fillRect(pad.l,7,12,12);c.fillStyle='#435466';c.fillText(aLabel,pad.l+18,17);c.fillStyle='#e07a2d';c.fillRect(pad.l+80,7,12,12);c.fillStyle='#435466';c.fillText(bLabel,pad.l+98,17)}
function formatMeasure(v,m){if(!Number.isFinite(v))return'—';return m==='epa'?v.toFixed(3):m==='yards'?v.toFixed(2):v.toFixed(2)+'%'}
function attachTooltip(canvas,items,pad,plotW,bw,textFn){canvas.onmousemove=e=>{const r=canvas.getBoundingClientRect(),x=e.clientX-r.left;if(x<pad.l||x>r.width-pad.r){$('tooltip').style.display='none';return}const i=Math.floor((x-pad.l)/(plotW/items.length));const it=items[i];if(!it){$('tooltip').style.display='none';return}const t=$('tooltip');t.textContent=textFn(it);t.style.left=(e.clientX+12)+'px';t.style.top=(e.clientY+12)+'px';t.style.display='block'};canvas.onmouseleave=()=>{$('tooltip').style.display='none'}}
function renderTable(){const start=page*PAGE_SIZE,end=Math.min(start+PAGE_SIZE,filtered.length),rows=filtered.slice(start,end);$('dataBody').innerHTML=rows.map(r=>`<tr><td>${r.season}</td><td>${r.week}</td><td>${r.posteam}</td><td>${r.defteam}</td><td>${r.qtr}</td><td>${r.down}</td><td>${r.ydstogo}</td><td>${Number.isFinite(r.yardline_100)?r.yardline_100:''}</td><td>${r.play_call}</td><td>${r.yards_gained}</td><td>${Number.isFinite(r.epa)?r.epa.toFixed(3):''}</td><td>${r.success===1?'Yes':'No'}</td></tr>`).join('');$('tableCount').textContent=filtered.length?`Showing ${(start+1).toLocaleString()}–${end.toLocaleString()} of ${filtered.length.toLocaleString()} matching plays`:'No matching plays';$('prevPage').disabled=page===0;$('nextPage').disabled=end>=filtered.length}
function debounce(fn,ms){let t;return()=>{clearTimeout(t);t=setTimeout(fn,ms)}}
fetch(DATA_URL).then(r=>{if(!r.ok)throw new Error('Could not load data');return r.text()}).then(text=>{allData=parseCSV(text);$('loading').hidden=true;$('dashboard').hidden=false;init()}).catch(err=>{$('loading').innerHTML=`<strong>Data could not be loaded.</strong><br>${err.message}<br><span class="note">For local testing, serve this folder with a small local web server rather than opening dashboard.html directly as a file.</span>`});
